### ISSUE TITLE
Error in install on MacOSX

### ISSUE THREAD

**Issue by cehyde** [JeffersonLab/F2c#1]
Here is my result on MacOSX 10.10.5
some system info at end

Charless-MacBook-Air:F2c-master hyde$ ./install
f2py -c --fcompiler=gnu95 -m fF2C  \
grv98.f  \
EPS09.f  \
slmach.f \
dqags.f  \
hq_usr_pdf.f \
hq_core_sfh.f 
make: f2py: Command not found
make: *** [makefile:12: pycode] Error 127
/Users/hyde/Documents/Research/EIC/OpenCharm-LDRD/NobuoSato/F2c-master
Charless-MacBook-Air:F2c-master hyde$ more install
#!/bin/bash
cd F2C
make pycode
cd -

Charless-MacBook-Air:F2c-master hyde$ which gcc
/usr/bin/gcc
Charless-MacBook-Air:F2c-master hyde$ which gfortran
/usr/local/bin/gfortran
Charless-MacBook-Air:F2c-master hyde$ which g++
/usr/bin/g++
Charless-MacBook-Air:F2c-master hyde$ which py
Charless-MacBook-Air:F2c-master hyde$ which make
/usr/local/bin/make
Charless-MacBook-Air:F2c-master hyde$ make --version
GNU Make 4.2
Built for x86_64-apple-darwin14.5.0
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Charless-MacBook-Air:F2c-master hyde$

**Comment by nobuosato** [comment]
Please install python2.XX distribution from Anaconda 
https://www.continuum.io/downloads
